apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-web
  labels:
    app: amazon-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon-web
  template:
    metadata:
      labels:
        app: amazon-web
    spec:
      containers:
      - name: amazon-web-container
        image: averma9/amazon-web:latest
        env:
          - name: MONGODB_URL
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGODB_URL

---

apiVersion: v1
kind: Service
metadata:
  name: amazon-web-service
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: amazon-web
  type: LoadBalancer 